apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  labels:
    app: influx-app
spec:
  type: NodePort
  ports:
  - port: 8086
    nodePort: 8086
    protocol: TCP
    name: http
  selector:
    app: influx-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx-app
  template:
    metadata:
      labels:
        app: influx-app
    spec:
      containers:
      - name: influxdb
        image: services/influxdb
        ports:
        - containerPort: 8086
        imagePullPolicy: Never