apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: services/nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        imagePullPolicy: Never
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  namespace: default
spec:
  rules:
  - host: ftservices.rchallie
  - http:
      paths:
      - path: /
        backend:
          serviceName: nginx-svc
          servicePort: 80
